### ISSUE TITLE
Error when parsing AWS lambda event from S3 bucket

### ISSUE THREAD

**Issue by sothawo** [http4k/http4k#1057]
Hello,

for tests I have written a small AWS lambda event handler:
```
package com.sothawo.kotlinlambda

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.events.S3Event
import org.http4k.serverless.AwsLambdaEventFunction
import org.http4k.serverless.FnHandler
import org.http4k.serverless.FnLoader

fun eventFnHandler() =
    FnHandler { s3Event: S3Event, _: Context ->
        s3Event.records.forEach {
            println(it.s3.bucket.name)
            println(it.s3.`object`.key)
        }
    }

fun eventFnLoader() =
    FnLoader { _: Map<String, String> ->
        eventFnHandler()
    }

class KotlinLambdaEventFunction : AwsLambdaEventFunction(eventFnLoader())
```
I have set up the IAM roles, deployed the zipped lambda and added a S3 bucket as trigger. This all went ok.

When I create an S3 event by adding to or deleting from the bucket the lambda is triggered but fails with:
```
unknown key: java.lang.IllegalStateException java.lang.IllegalStateException: unknown key at org.http4k.format.S3EventAdapterKt$responseElements$2.in

unknown key: java.lang.IllegalStateException
java.lang.IllegalStateException: unknown key
	at org.http4k.format.S3EventAdapterKt$responseElements$2.invoke(S3EventAdapter.kt:184)
	at org.http4k.format.S3EventAdapterKt$responseElements$2.invoke(S3EventAdapter.kt:180)
	at org.http4k.format.ReadKt.obj(read.kt:17)
	at org.http4k.format.S3EventAdapterKt.responseElements(S3EventAdapter.kt:180)
	at org.http4k.format.S3EventAdapterKt.access$responseElements(S3EventAdapter.kt:1)
	at org.http4k.format.S3EventAdapter$fromJson$1$2.invoke(S3EventAdapter.kt:48)
	at org.http4k.format.S3EventAdapter$fromJson$1$2.invoke(S3EventAdapter.kt:28)
	at org.http4k.format.ReadKt.obj(read.kt:17)
	at org.http4k.format.S3EventAdapter.fromJson(S3EventAdapter.kt:28)
	at org.http4k.format.S3EventAdapter.fromJson(S3EventAdapter.kt:17)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:58)
	at org.http4k.format.ConfigurableMoshi.asA(ConfigurableMoshi.kt:98)
	at org.http4k.serverless.AutoMarshallingFnLoader.invoke$lambda$0(AutoMarshallingFnLoader.kt:19)
	at org.http4k.serverless.AwsLambdaEventFunction.handleRequest(AwsLambdaEventFunction.kt:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

Looking at the code for `S3EventAdapter` this happens when parsing the responseElements:
```
private fun JsonReader.responseElements() =
    obj({ it -> ResponseElementsEntity(it["xAmzId2"] as? String, it["xAmzRequestId"] as? String) }) {
        when (it) {
            "xAmzId2" -> nextString()
            "xAmzRequestId" -> nextString()
            else -> error("unknown key")
        }
    }
```
The adapter expects camel-cased properties, but the event has them in kebab-case ('x-amz-id-2" and "x-amz-request-id"). This is reproducible in the AWS browser console. First using a test event provided by AWS it fails, after switching to camelcase it works.

this fails:
<img width="1054" alt="image" src="https://github.com/http4k/http4k/assets/8456476/80bf88de-5a51-4200-9bf2-5da5b9b617b1">

this works:
<img width="1477" alt="image" src="https://github.com/http4k/http4k/assets/8456476/91ab5e1d-cee6-4c9d-acd3-6351c1a2d45f">

**Comment by sothawo** [comment]
Wow, that was fast.
I just wanted to create a PR and was looking for issue and found it closed ;-)

My change would have been:
```
private fun JsonReader.responseElements() =
    obj({ it -> ResponseElementsEntity(it["xAmzId2"] as? String, it["xAmzRequestId"] as? String) }) {
        when (it) {
            "xAmzId2", "x-amz-id-2" -> nextString()
            "xAmzRequestId", "x-amz-request-id" -> nextString()
            else -> error("unknown key")
        }
    }
```
to keep the possibility of both spellings (you never know what AWS really wants).

But thanks for that fast response and fix.

**Comment by daviddenton** [comment]
no worries. The offical docs list the - cased version - it was an oversight of ours when creating the module in the first place. If it still turns out to be a problem we can update again.

**Comment by daviddenton** [comment]
Releasing this in a few minutes :)
