### ISSUE TITLE
GraalVM: Supply reflect-config.json to Native Compilation

### ISSUE THREAD

**Issue by asleson** [http4k/http4k#1137]
I am trying to compile my http4k app to native using GraalVM [using the supplied instructions](https://www.http4k.org/guide/tutorials/going_native_with_graal_on_aws_lambda/).  I was able to create the binary and deploy it to AWS.  I know the native binary works (at least a little) because the simple `/ping` endpoint works.

When I tested a more complex `POST` endpoint that converts the posted JSON body to a Kotlin class, it fails with this message:

```
... 50 more
Caused by: java.lang.IllegalArgumentException: Type com.xyz.models.ExecuteTemplateInputs is instantiated reflectively but was never registered. Register the type by adding "unsafeAllocated" for the type in reflect-config.json.
at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.instanceHubErrorStub(SubstrateAllocationSnippets.java:315)
at jdk.unsupported@22.0.1/sun.misc.Unsafe.allocateInstance(Unsafe.java:848)
... 53 more
```

If it helps, the app is using GSON for the JSON serialization, using the patterns mentioned in the docs.

I'm new to native compilation via the GraalVM, but I quickly recognized this error from when I've read previous articles on the topic.  I did some digging, and it looks like I need to create a `reflect-config.json` file that would look like this, for my case:

```
[
  {
    "name": "com.xyz.models.ExecuteTemplateInputs",
    "unsafeAllocated": true
  }
]
```

That seems easy enough, but.... how can I do that?  I used the recommended command to create the native binary, but that doesn't seem to have a way to specify the `reflect-config.json` file.  

I also [looked at the Docker files in the repo](https://github.com/http4k/docker-images/blob/master/amazonlinux-java-graal-community-lambda-runtime/packageZip) and I don't see the `reflect-config.json` file mentioned.

Can you please add support for this `reflect-config.json` file?  Or, point me to how I would do it myself?

Thank you!

**Comment by daviddenton** [comment]
I have a recommendation for you to completely avoid GSON and hopefully this will make your problems disappear. 🙃 

For a start, GSON really isn't the library to be using with Kotlin - it doesn't support the type system correctly. The accepted solution is to use Jackson or Moshi instead.

Additionally, you can avoid the use of reflection entirely by using generated adapters using a combination of [Moshi](https://github.com/square/moshi) and [Kotshi](https://github.com/ansman/kotshi), Basically by annotating your types with @JsonSerializable, you can get gradle to generate the converters at compile time. This will allow you to exclude Kotlin-reflect entirely at runtime which will have a much better effect on both your ZIP size and the lambda performance.

**Comment by asleson** [comment]
That makes perfect sense.  Thank you for the explanation!  I'm unfamiliar with Moshi and Kotshi but those look like great options.  Thank you so much for the helpful explanation! I appreciate it!
