### ISSUE TITLE
Accidental module classpath requirement breaks Jackson/Moshi/etc with NoClassDefFoundError : v5.37.0.0 and 5.37.1.0

### ISSUE THREAD

**Issue by daviddenton** [http4k/http4k#1225]
Received stack:

```
Caused by: java.lang.NoClassDefFoundError: org/http4k/datastar/Signal
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3609)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3609)
	at java.base/java.lang.Class.getMethods(Class.java:2185)
```

**Comment by daviddenton** [comment]
This is fixed in 5.37.1.1
