### ISSUE TITLE
Multipart requests: Boundary not found error when request stream has been materialized

### ISSUE THREAD

**Issue by karottenreibe** [http4k/http4k#123]
When running this program:

```kotlin
import org.http4k.core.MultipartFormBody
import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status
import org.http4k.server.Jetty
import org.http4k.server.asServer

fun main(args: Array<String>) {
    val app = { request: Request ->
        println(request)
        println(MultipartFormBody.from(request).file("file"))
        Response(Status.OK)
    }

    app.asServer(Jetty(8000)).start()
}
```

and uploading a file with curl to it: `curl http://localhost:8000 -Ffile=@foo.txt`

I get this error:

```
2018-04-20 09:51:42 [WARN ] org.eclipse.jetty.server.HttpChannel - /
org.http4k.multipart.ParseError: org.http4k.multipart.TokenNotFoundException: Boundary not found <<--------------------------44f349e8bc402dd4>>
	at org.http4k.multipart.StreamingMultipartFormParts$StreamingMulipartFormPartIterator.safelyParseNextPart(StreamingMultipartFormParts.kt:175) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.multipart.StreamingMultipartFormParts$StreamingMulipartFormPartIterator.hasNext(StreamingMultipartFormParts.kt:142) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.multipart.MultipartFormParser.formParts(MultipartFormParser.kt:42) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.core.MultipartFormBody$Companion.from(MultipartFormBody.kt:64) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.core.MultipartFormBody$Companion.from$default(MultipartFormBody.kt:59) ~[http4k-multipart-3.24.0.jar:?]
	at TestKt$main$app$1.invoke(Test.kt:11) ~[classes/:?]
	at TestKt$main$app$1.invoke(Test.kt) ~[classes/:?]
	at org.http4k.servlet.HttpHandlerServlet.service(servlet.kt:19) ~[http4k-core-3.24.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791) ~[javax.servlet-api-4.0.0.jar:4.0.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) ~[jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) ~[jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.handle(Server.java:561) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) ~[jetty-io-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104) ~[jetty-io-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) ~[jetty-io-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: org.http4k.multipart.TokenNotFoundException: Boundary not found <<--------------------------44f349e8bc402dd4>>
	at org.http4k.multipart.StreamingMultipartFormParts.findBoundary(StreamingMultipartFormParts.kt:39) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.multipart.StreamingMultipartFormParts.parseNextPart(StreamingMultipartFormParts.kt:61) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.multipart.StreamingMultipartFormParts.access$parseNextPart(StreamingMultipartFormParts.kt:13) ~[http4k-multipart-3.24.0.jar:?]
	at org.http4k.multipart.StreamingMultipartFormParts$StreamingMulipartFormPartIterator.safelyParseNextPart(StreamingMultipartFormParts.kt:171) ~[http4k-multipart-3.24.0.jar:?]
	... 32 more
```

After some debugging, I understand that this happens because the MultipartFormBody tries to read from the request's input stream, which has already been depleted and materialized into a byte array due to logging the request in the line above.

I would expect that in this case either

- the MultipartFormBody would just read from the byte array if the stream is materialized
- or alternatively, it at least outputs a more helpful error message

The current error message made me assume that something was wrong with the request that was being sent, sending me on a long goose chase to debug the actual request. An error message like "Cannot read multipart data after stream has been materialized" would be a little more helpful.

Reading from the materialized byte array is the best solution IMO, though. 

I understand that materializing the request comes with its own problems (e.g. if the requests are large), however, there are valid scenarios where one would want to do it anyways (e.g. during debugging) and then this error is not helpful, unfortunately.

**Comment by daviddenton** [comment]
We do know that using streaming plus debugging is a source for trouble - we saw this with the stream body and in memory body implementations. We solved it there so would be able to do something similar with this scenario. 🤞

**Comment by daviddenton** [comment]
Preliminary investigations indicate that this is going to be a bit difficult - the Multipart code is quite involved. Will continue to look... :( 

As an aside, you can use a debugging filter and ignore streams, which should give you the opportunity to at least view the rest of your requests if required. ```PrintRequestAndResponse(debugStream = false)```

**Comment by daviddenton** [comment]
As an aside, you can use a debugging filter and ignore streams, which should give you the opportunity to at least view the rest of your requests if required. ```PrintRequestAndResponse(debugStream = false).the(app)``` will give you that. I'm just releasing the change to enable this now.

**Comment by daviddenton** [comment]
Found a simple fix. Releasing in 3.26.4 :)
