### ISSUE TITLE
Documentation: Wrong Wildcard Pattern Shown for Routers

### ISSUE THREAD

**Issue by commonsguy** [http4k/http4k#136]
https://www.http4k.org/guide/modules/core/

In the section on routers, you have:

```kotlin
routes(
    "/hello" bind routes(
        "/{name:*}" bind GET to { request: Request -> Response(OK).body("Hello, ${request.path("name")}!") }
    ),
    "/fail" bind POST to { request: Request -> Response(INTERNAL_SERVER_ERROR) }
).asServer(Jetty(8000)).start()
```

However, this `{name:*}` wildcard syntax crashes with:

```
Exception in thread "main" java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 1
(*)
 ^
        at java.util.regex.Pattern.error(Pattern.java:1955)
        at java.util.regex.Pattern.sequence(Pattern.java:2123)
        at java.util.regex.Pattern.expr(Pattern.java:1996)
        at java.util.regex.Pattern.group0(Pattern.java:2905)
        at java.util.regex.Pattern.sequence(Pattern.java:2051)
        at java.util.regex.Pattern.expr(Pattern.java:1996)
        at java.util.regex.Pattern.compile(Pattern.java:1696)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at kotlin.text.Regex.<init>(Regex.kt:92)
        at org.http4k.core.UriTemplate.<init>(UriTemplate.kt:18)
```

Switching to `{name:.*}` works.

Later in the same page, `"/hello/{date:*}"` is shown, which may result in the same error.

**Comment by daviddenton** [comment]
Fixed. Thanks for the spot. :)
