### ISSUE TITLE
Gzip filters send content-encoding of gzip even when body is empty

### ISSUE THREAD

**Issue by jshiell** [http4k/http4k#338]
Using the Apache client and a streaming Gzip server filter, we get EOF exceptions for Gzipped requests. This occurs with both the in-memory and streaming client Gzip filters.

My working theory is that the Apache client is discarding the bodies for Gzipped GET requests, yet we still send the content-encoding header, resulting in:
```
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "GET /a/path HTTP/1.1[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "User-Agent: app/SNAPSHOT[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "x-b3-traceid: ac5dc23498af2e04[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "x-b3-spanid: c2fa461167d886e9[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "x-b3-sampled: 1[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "content-encoding: gzip[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "Host: localhost:8080[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "Connection: Keep-Alive[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "Accept-Encoding: gzip,deflate[\r][\n]" 
09:32:25.107 [] DEBUG org.apache.http.wire - http-outgoing-65 >> "[\r][\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "HTTP/1.1 500 Server Error[\r][\n]" 
<snipped>

09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "<h3>Caused by:</h3><pre>java.io.EOFException[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:269)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:259)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at java.base/java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:80)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at java.base/java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:92)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.filter.ExtKt.gunzippedStream(ext.kt:38)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.filter.GzipCompressionMode$Streaming$2.invoke(ext.kt:18)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.filter.GzipCompressionMode$Streaming$2.invoke(ext.kt:18)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.filter.RequestFilters$GunZip$invoke$1$1.invoke(RequestFilters.kt:43)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.filter.RequestFilters$GunZip$invoke$1$1.invoke(RequestFilters.kt:38)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt:19)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.routing.TemplateRoutingHttpHandler$match$1.invoke(internal.kt:92)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.routing.TemplateRoutingHttpHandler$match$1.invoke(internal.kt:83)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.routing.AggregateRoutingHttpHandler.invoke(internal.kt:71)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.routing.AggregateRoutingHttpHandler.invoke(internal.kt:65)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.http4k.servlet.HttpHandlerServlet.service(servlet.kt:19)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.Server.handle(Server.java:500)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)[\n]" 
09:32:25.109 [] DEBUG org.apache.http.wire - http-outgoing-65 << "[0x9]at java.base/java.lang.Thread.run(Thread.java:834)[\n]" 
```

I believe the fix will need two parts - firstly, that we don't send empty bodies with a misleading encoding (affects both in-memory/streaming); secondly, that the streaming decoder is tolerant of empty streams.

I'm working on these; this is more a notification to let people know I'm on it, rather than a bug report.

**Comment by daviddenton** [comment]
Thanks for picking this up @jshiell 🙂

**Comment by daviddenton** [comment]
Is this fully fixed now then @jshiell  ?

**Comment by daviddenton** [comment]
Regardless, releasing this in 3.211.0

**Comment by jshiell** [comment]
@daviddenton hopefully - I’ll tell you tomorrow when I find the next set of bugs. Cheers!
