### ISSUE TITLE
Entering double value crashes the contract doc

### ISSUE THREAD

**Issue by abs-zero** [http4k/http4k#380]
If I pass a double value 400.0 like below:
```kotlin
data class Foo(val x: Double)

// inside some route handler
return "/foo" meta {
    summary = "foo"
    receiving(someFooLens to Foo(400.0))
}
``` 
I get exception as shown below when I hit OpenApi doc route
```
java.lang.NumberFormatException: Illegal embedded sign character
	at java.base/java.math.BigInteger.<init>(BigInteger.java:498)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:672)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.numberSchema(JsonToJsonSchema.kt:32)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.toSchema(JsonToJsonSchema.kt:22)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.toSchema$default(JsonToJsonSchema.kt:16)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.objectSchema(JsonToJsonSchema.kt:48)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.toSchema(JsonToJsonSchema.kt:18)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.toSchema$default(JsonToJsonSchema.kt:16)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.objectSchema(JsonToJsonSchema.kt:48)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.toSchema(JsonToJsonSchema.kt:18)
	at org.http4k.contract.openapi.v3.JsonToJsonSchema.toSchema(JsonToJsonSchema.kt:14)
	at org.http4k.contract.openapi.v3.OpenApi3.toSchema(OpenApi3.kt:191)
	at org.http4k.contract.openapi.v3.OpenApi3.toSchemaContent(OpenApi3.kt:185)
	at org.http4k.contract.openapi.v3.OpenApi3.collectSchemas(OpenApi3.kt:129)
	at org.http4k.contract.openapi.v3.OpenApi3.responses(OpenApi3.kt:122)
	at org.http4k.contract.openapi.v3.OpenApi3.apiPath(OpenApi3.kt:97)
	at org.http4k.contract.openapi.v3.OpenApi3.asPath(OpenApi3.kt:83)
	at org.http4k.contract.openapi.v3.OpenApi3.description(OpenApi3.kt:62)
	at org.http4k.contract.ContractRoutingHttpHandler$$special$$inlined$let$lambda$1.invoke(ContractRoutingHttpHandler.kt:52)
	at org.http4k.contract.ContractRoutingHttpHandler$$special$$inlined$let$lambda$1.invoke(ContractRoutingHttpHandler.kt:20)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt:15)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt:15)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt)
	at org.http4k.filter.ResponseFilters$ReportHttpTransaction$invoke$2$1.invoke(ResponseFilters.kt:34)
	at org.http4k.filter.ResponseFilters$ReportHttpTransaction$invoke$2$1.invoke(ResponseFilters.kt:30)
	at org.http4k.filter.DebuggingFilters$PrintResponse$invoke$1$1.invoke(DebuggingFilters.kt:28)
	at org.http4k.filter.DebuggingFilters$PrintResponse$invoke$1$1.invoke(DebuggingFilters.kt:24)
	at org.http4k.filter.RequestFilters$Tap$invoke$1$1.invoke(RequestFilters.kt:19)
	at org.http4k.filter.RequestFilters$Tap$invoke$1$1.invoke(RequestFilters.kt:15)
	at com.eventsmo.MainKt$main$2$1.invoke(Main.kt:163)
	at com.eventsmo.MainKt$main$2$1.invoke(Main.kt)
	at com.eventsmo.filters.CatchExceptionsFilter$invoke$1$1.invoke(CatchExceptionsFilter.kt:15)
	at com.eventsmo.filters.CatchExceptionsFilter$invoke$1$1.invoke(CatchExceptionsFilter.kt:11)
	at org.http4k.filter.ServerFilters$CatchLensFailure$2$1.invoke(ServerFilters.kt:199)
	at org.http4k.filter.ServerFilters$CatchLensFailure$2$1.invoke(ServerFilters.kt:42)
	at org.http4k.filter.ServerFilters$InitialiseRequestContext$invoke$1$1.invoke(ServerFilters.kt:271)
	at org.http4k.filter.ServerFilters$InitialiseRequestContext$invoke$1$1.invoke(ServerFilters.kt:266)
	at org.http4k.contract.ContractRoutingHttpHandler$identify$1$1$1.invoke(ContractRoutingHttpHandler.kt:83)
	at org.http4k.contract.ContractRoutingHttpHandler$identify$1$1$1.invoke(ContractRoutingHttpHandler.kt:20)
	at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt:19)
	at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt)
	at org.http4k.routing.AggregateRoutingHttpHandler.invoke(internal.kt:71)
	at org.http4k.routing.AggregateRoutingHttpHandler.invoke(internal.kt:65)
	at org.http4k.filter.ServerFilters$CatchAll$invoke$1$1.invoke(ServerFilters.kt:218)
	at org.http4k.filter.ServerFilters$CatchAll$invoke$1$1.invoke(ServerFilters.kt:214)
	at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt:19)
	at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt)
	at org.http4k.server.Http4kChannelHandler.channelRead0(Netty.kt:50)
	at org.http4k.server.Http4kChannelHandler.channelRead0(Netty.kt:43)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The issue doesn't occur if I enter value 0.0 instead of 400.0

**Comment by daviddenton** [comment]
This seems to be related to how Jackson serlialises exact double values. I'm not sure of the fix just yet (as it might involved digging into the config of Jackson for doubles), but as a workaround, setting the example values to a non-exact double value should work.

**Comment by daviddenton** [comment]
I'm not sure if this has been fixed with the latest version of Jackson, but with this code I can't recreate the problem, so am closing this. 

Please try upgrading and reopen if it's still a problem @abs-zero . Thanks.

```

import org.http4k.contract.contract
import org.http4k.contract.meta
import org.http4k.contract.openapi.ApiInfo
import org.http4k.contract.openapi.v3.OpenApi3
import org.http4k.core.Body
import org.http4k.core.Method.GET
import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status.Companion.OK
import org.http4k.format.Jackson
import org.http4k.format.Jackson.auto

data class Foo(val x: Double)

fun main() {
    val http = contract {
        renderer = OpenApi3(ApiInfo("123", "123"), Jackson)
        routes += "/foo" meta {
            summary = "foo"
            receiving(Body.auto<Foo>().toLens() to Foo(400.0))
        } bindContract GET to { Response(OK) }
    }

    println(http(Request(GET, "/")))
}
```
