### ISSUE TITLE
SunHttp throws (silent) exception when returning 204

### ISSUE THREAD

**Issue by ToastShaman** [http4k/http4k#598]
SunHttp throws an exception (silently swallowed) when used with Http4k when trying to return a NO_CONTENT response. Here's a test to reproduce.

```
    @Test
    fun `SunHttp throws exception when returning NO_CONTENT`() {
        val app = { _: Request -> Response(NO_CONTENT) }
        val server = app.asServer(SunHttp(8000))
        server.start()
        println(ApacheClient()(Request(GET, "http://localhost:8000/hello")))
        server.stop()
    }
```

```
WARNING: sendResponseHeaders: rCode = 204: forcing contentLen = -1
Exception in thread "pool-1-thread-1" java.lang.AssertionError
	at jdk.httpserver/sun.net.httpserver.WriteFinishedEvent.<init>(WriteFinishedEvent.java:31)
	at jdk.httpserver/sun.net.httpserver.FixedLengthOutputStream.close(FixedLengthOutputStream.java:99)
	at jdk.httpserver/sun.net.httpserver.PlaceholderOutputStream.close(ExchangeImpl.java:459)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:57)
	at uk.nhs.nhsx.testhelper.s3.FoobarT$sunHttp$1.handle(Foobar.kt:28)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

After some investigation it seems to be caused by a race condition in conjunction with the way Http4k copies the response body into the Outputsream.

```
    @Test
    fun `Http4k equivalent`() {
        val address = InetSocketAddress(8000)
        val httpServer = HttpServer.create(address, 1000)
        httpServer.executor = Executors.newWorkStealingPool()

        httpServer.createContext("/hello") { exchange ->
            exchange.sendResponseHeaders(HttpURLConnection.HTTP_NO_CONTENT, 0)
            exchange.responseBody.use { ByteArrayInputStream("".toByteArray()).copyTo(it) }
            exchange.close()
        }

        httpServer.start()

        println(ApacheClient()(Request(GET, "http://localhost:8000/hello")))

        httpServer.stop(0)
    }
```

* Removing the `executor` makes the exception go away
* Keeping the `executor` but not closing the `exchange.responseBody` makes the exception go away

**Comment by daviddenton** [comment]
The second one doesn't solve the problem.. :) 

```
Mar 19, 2021 4:00:08 PM sun.net.httpserver.ExchangeImpl sendResponseHeaders
WARNING: sendResponseHeaders: rCode = 204: forcing contentLen = -1
Exception in thread "ForkJoinPool-2-worker-19" java.lang.AssertionError
	at jdk.httpserver/sun.net.httpserver.WriteFinishedEvent.<init>(WriteFinishedEvent.java:31)
```
