### ISSUE TITLE
Out Of Memory when handling an about 100MB upload

### ISSUE THREAD

**Issue by anthonybriand** [http4k/http4k#642]
Hello,

I'm trying to handle an HTTP upload with http4k on Android (tested with backends : apache, netty) and when I call the MultiparFormBody.from the application crash with the given error :
```
java.lang.OutOfMemoryError: Failed to allocate a 134217744 byte allocation with 25165824 free bytes and 124MB until OOM, target footprint 96238408, growth limit 201326592
        at java.util.Arrays.copyOf(Arrays.java:3161)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:108)
        at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
        at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:136)
        at org.http4k.core.StreamBody$payload$2.invoke(http.kt:71)
        at org.http4k.core.StreamBody$payload$2.invoke(http.kt:70)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.http4k.core.StreamBody.getPayload(Unknown Source:2)
        at org.http4k.core.MultipartFormBody$Companion.from(MultipartFormBody.kt:86)
        at org.http4k.core.MultipartFormBody$Companion.from$default(MultipartFormBody.kt:84)
        at xx.xxxxx.xxxxxxxxx.xxxxx.PVU$Companion.handle(PVU.kt:20)
        at xx.xxxxx.xxxxxxxxx.xxxxx.HS$Companion$start$1$1$8.invoke(HS.kt:43)
        at xx.xxxxx.xxxxxxxxx.xxxxx.HS$Companion$start$1$1$8.invoke(HS.kt:43)
        at org.http4k.routing.TemplateRouter$match$1.invoke(Router.kt:147)
        at org.http4k.routing.TemplateRouter$match$1.invoke(Router.kt:141)
        at org.http4k.routing.RouterMatch$MatchingHandler.invoke(Router.kt:47)
        at org.http4k.routing.RouterMatch$MatchingHandler.invoke(Router.kt:46)
        at org.http4k.routing.RouterBasedHttpHandler.invoke(RouterBasedHttpHandler.kt:23)
        at org.http4k.routing.RouterBasedHttpHandler.invoke(RouterBasedHttpHandler.kt:13)
        at org.http4k.filter.ServerFilters$CatchAll$invoke$1$1.invoke(ServerFilters.kt:259)
        at org.http4k.filter.ServerFilters$CatchAll$invoke$1$1.invoke(ServerFilters.kt:255)
        at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt:15)
        at org.http4k.core.Http4kKt$then$2.invoke(Unknown Source:2)
        at org.http4k.server.Http4kRequestHandler.handle(ApacheServer.kt:41)
        at org.apache.hc.core5.http.io.support.BasicHttpServerRequestHandler.handle(BasicHttpServerRequestHandler.java:75)
        at org.apache.hc.core5.http.io.support.BasicHttpServerExpectationDecorator.handle(BasicHttpServerExpectationDecorator.java:87)
        at org.apache.hc.core5.http.impl.io.HttpService.handleRequest(HttpService.java:190)
        at org.apache.hc.core5.http.impl.bootstrap.Worker.run(Worker.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
It seems that multipart module try to load in memory the full uploaded file, in my case about 100MB, when I just want to get the InputStream in order to make some treatment

I searched some options to prevent this, but without success.

My routes declarations and server start :
```
app = routes(
    "prefix/v/u" bind Method.POST to { request -> PVU.handle(request) },
)

server = app?.asServer(ApacheServer(3000))?.start()
```

My handler :
```
fun handle(request: Request): Response {
    US.uV(MultipartFormBody.from(request).file("file")) // here is the problem, I don't enter into my method due to the above exception

    return Response(Status.CREATED)
}
```

I don't see what I missed

Thank you in advance for your responses.

**Comment by anthonybriand** [comment]
I have tested with `largeHeap` to `true` same error :
```
E/AndroidRuntime: FATAL EXCEPTION: HTTP-worker-4
    Process: xx.xxxxx.xxxxxxxxx.xxxxx, PID: 24146
    java.lang.OutOfMemoryError: Failed to allocate a 1073741840 byte allocation with 25165824 free bytes and 406MB until OOM, target footprint 135792376, growth limit 536870912
        at org.http4k.multipart.MultipartFormParser.formParts(MultipartFormParser.kt:40)
        at org.http4k.core.MultipartFormBody$Companion.from(MultipartFormBody.kt:90)
        at xx.xxxxx.xxxxxxxxx.xxxxx.PVU$Companion.handle(PostVisitUpload.kt:20)
        at xx.xxxxx.xxxxxxxxx.xxxxx.HS$Companion$start$1$1$8.invoke(HttpServer.kt:43)
        at xx.xxxxx.xxxxxxxxx.xxxxx.HS$Companion$start$1$1$8.invoke(HttpServer.kt:43)
        at org.http4k.routing.TemplateRouter$match$1.invoke(Router.kt:147)
        at org.http4k.routing.TemplateRouter$match$1.invoke(Router.kt:141)
        at org.http4k.routing.RouterMatch$MatchingHandler.invoke(Router.kt:47)
        at org.http4k.routing.RouterMatch$MatchingHandler.invoke(Router.kt:46)
        at org.http4k.routing.RouterBasedHttpHandler.invoke(RouterBasedHttpHandler.kt:23)
        at org.http4k.routing.RouterBasedHttpHandler.invoke(RouterBasedHttpHandler.kt:13)
        at org.http4k.filter.ServerFilters$CatchAll$invoke$1$1.invoke(ServerFilters.kt:259)
        at org.http4k.filter.ServerFilters$CatchAll$invoke$1$1.invoke(ServerFilters.kt:255)
        at org.http4k.core.Http4kKt$then$2.invoke(Http4k.kt:15)
        at org.http4k.core.Http4kKt$then$2.invoke(Unknown Source:2)
        at org.http4k.server.Http4kRequestHandler.handle(ApacheServer.kt:41)
        at org.apache.hc.core5.http.io.support.BasicHttpServerRequestHandler.handle(BasicHttpServerRequestHandler.java:75)
        at org.apache.hc.core5.http.io.support.BasicHttpServerExpectationDecorator.handle(BasicHttpServerExpectationDecorator.java:87)
        at org.apache.hc.core5.http.impl.io.HttpService.handleRequest(HttpService.java:190)
        at org.apache.hc.core5.http.impl.bootstrap.Worker.run(Worker.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by s4nchez** [comment]
To ensure streams are not fully consumed for multipart forms, you need to follow a slightly different approach:

https://www.http4k.org/guide/howto/use_multipart_forms/#streaming_-_iterate_over_multiparts

Could you give it a try and let us know if you still face the same issue?

**Comment by anthonybriand** [comment]
Hi, thank you for your response, I have tried and it worked as expected.

Sorry for the inconvenience, I haven't seen this section in the guide.
