### ISSUE TITLE
contract with nullable body parameter is crashing with: java.lang.NoSuchMethodError: java.lang.reflect.Field.trySetAccessible() JVM 1.8

### ISSUE THREAD

**Issue by dbacinski** [http4k/http4k#648]
When I am trying to generate contract with null in model openapi.json http4k is crashing with:
```
Exception in thread "HTTP-worker-3" java.lang.NoSuchMethodError: java.lang.reflect.Field.trySetAccessible()Z
	at org.http4k.contract.openapi.v3.SimpleLookup.invoke(FieldRetrieval.kt:38)
	at org.http4k.contract.openapi.v3.JacksonJsonNamingAnnotated.invoke(jacksonExt.kt:50)
	at org.http4k.contract.openapi.v3.JacksonJsonNamingAnnotated.invoke(jacksonExt.kt:46)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1$1.invoke(FieldRetrieval.kt:13)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1$1.invoke(FieldRetrieval.kt:9)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1.invoke(FieldRetrieval.kt:17)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1.invoke(FieldRetrieval.kt:10)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1$1.invoke(FieldRetrieval.kt:13)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1$1.invoke(FieldRetrieval.kt:9)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1.invoke(FieldRetrieval.kt:17)
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1.invoke(FieldRetrieval.kt:10)
	at org.http4k.contract.openapi.v3.AutoJsonToJsonSchema.toObjectSchema(AutoJsonToJsonSchema.kt:98)
	at org.http4k.contract.openapi.v3.AutoJsonToJsonSchema.toObjectOrMapSchema(AutoJsonToJsonSchema.kt:82)
	at org.http4k.contract.openapi.v3.AutoJsonToJsonSchema.toSchema(AutoJsonToJsonSchema.kt:35)
	at org.http4k.contract.openapi.v3.AutoJsonToJsonSchema.toSchema(AutoJsonToJsonSchema.kt:25)
	at org.http4k.contract.openapi.ApiRenderer$Companion$Auto$fallbackSchema$1.toSchema(ApiRenderer.kt:30)
	at org.http4k.contract.openapi.ApiRenderer$Companion$Auto$1.toSchema(ApiRenderer.kt)
	at org.http4k.contract.openapi.v3.OpenApi3.toSchemaContent(OpenApi3.kt:205)
	at org.http4k.contract.openapi.v3.OpenApi3.requestBody(OpenApi3.kt:172)
	at org.http4k.contract.openapi.v3.OpenApi3.apiPath(OpenApi3.kt:100)
	at org.http4k.contract.openapi.v3.OpenApi3.asPath(OpenApi3.kt:94)
	at org.http4k.contract.openapi.v3.OpenApi3.description(OpenApi3.kt:70)
	at org.http4k.contract.ContractRoutingHttpHandler$$special$$inlined$let$lambda$1.invoke(ContractRoutingHttpHandler.kt:66)
	at org.http4k.contract.ContractRoutingHttpHandler$$special$$inlined$let$lambda$1.invoke(ContractRoutingHttpHandler.kt:26)
	at org.http4k.routing.RouterMatch$MatchingHandler.invoke(Router.kt:47)
	at org.http4k.routing.RouterMatch$MatchingHandler.invoke(Router.kt:46)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt:11)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt:11)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt:11)
	at org.http4k.core.Http4kKt$NoOp$1$1.invoke(Http4k.kt)
	at org.http4k.filter.ResponseFilters$ReportHttpTransaction$invoke$2$1.invoke(ResponseFilters.kt:48)
	at org.http4k.filter.ResponseFilters$ReportHttpTransaction$invoke$2$1.invoke(ResponseFilters.kt:40)
	at org.http4k.filter.RequestFilters$Tap$invoke$1$1.invoke(RequestFilters.kt:23)
	at org.http4k.filter.RequestFilters$Tap$invoke$1$1.invoke(RequestFilters.kt:19)
```
It might have something to do with JVM/Java version which is 1.8 (I can't upgrade due to some legacy dependencies in a project)
Runtime: azul-1.8.0_292

It is only happening when I assign null to one of the model params otherwise it works.
```
     receiving(
            cart to CatalogCart(
                cartId = "",
                userId = null,  //assigning null here is causing docs generation to crash
            )
        )
```

Full contract:
```
            contract {
                renderer = OpenApi3(
                    ApiInfo("KK API", "v1.0", "KK API"),
                    Jackson,
                    emptyList(),
                    ApiRenderer.Auto(Jackson, AutoJsonToJsonSchema(Jackson)),
                    SecurityRenderer(AuthTokenFilter.AuthTokenSecurity.renderer),
                )
                descriptionPath = "/openapi.json"
                security = AuthTokenFilter.AuthTokenSecurity(authTokenFilter)

                routes +=  "/cart" meta CartCreate bindContract  Method.POST to cartHandler.handleCreateCart()
  }

   val cart = Body.auto<CatalogCart>().toLens()

   val CartCreate: RouteMetaDsl.() -> Unit = {
        summary = "Create new cart and get cart id"
        produces += ContentType.APPLICATION_JSON
        receiving(
            cart to CatalogCart(
                cartId = "",
                userId = null,  //assigning null here is causing docs generation to crash
            )
        )
        returning(
            OK,
            cart to CatalogCart(
                cartId = "uuid",
                userId = 123,
            )
        )
    }

@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
@JsonInclude(JsonInclude.Include.USE_DEFAULTS)
data class CatalogCart(
    val cartId: String,
    val userId: Int?,
) 

```

**Comment by dbacinski** [comment]
https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/AccessibleObject.html#trySetAccessible--

according to this trySetAccessible was introduced in Java 9.

**Comment by daviddenton** [comment]
Yes. We don't officially support Java 8 because it's not the LTS release and we decided that we couldn't support it forever. If there's a workaround then PR it for J8 and will.merge it.

Also, fyi - you can't use null in a model for OpenApi because we can't determine the type. It's a limitation.

Closing this now but please mention it if you PR the change.
