### ISSUE TITLE
Lens error on getObject for S3 files

### ISSUE THREAD

**Issue by AndreVelde** [http4k/http4k#824]
Currently trying to upgrade to the latest Http4K version but have a breaking issue from 4.33.0.0 to 4.33.1.0.
Sadly the patch notes don't mention anything about a breaking change and it seems like something is broken in the http4k-connect library.

I have the following code:
```
class S3Service {
    private val logger: Logger = LoggerFactory.getLogger(S3Service::class.java)
    private val s3Client: S3Bucket = S3Bucket.Http(bucketName = BUCKET_NAME, bucketRegion = REGION, http = OkHttp())

    fun getFromS3InputStream(fileName: String): InputStream? {
        val keyName = BucketKey.of(fileName)
        val result = s3Client.getObject(keyName)
        result.failureOrNull()?.let {
            logger.warn(
                "errorMessage" to it.message.toString(),
                "fileName" to fileName
            ) { "Failed to get S3 file" }
        }

        logger.info("Retrieved $fileName existed: ${result.valueOrNull() != null}")
        return result.valueOrNull()
    }

    companion object {
        val BUCKET_NAME = BucketName.of(Environment.getEnvironment("BACKENDS_SPOORKAART_S3_BUCKETNAME"))
        val REGION = Region.of(Environment.getEnvironment("AWS_REGION"))
    }
}
```

But the `s3Client.getObject(keyName)` gives the following error:
```
Request error java.lang.NoSuchMethodError: 'org.http4k.lens.Lens org.http4k.lens.LensSpec.required$default(org.http4k.lens.LensSpec, java.lang.String, java.lang.String, int, java.lang.Object)'
	at org.http4k.connect.amazon.ExtensionsKt.<clinit>(extensions.kt:16)
	at org.http4k.connect.amazon.CredentialsProviderKt.Environment$lambda-0(CredentialsProvider.kt:10)
	at org.http4k.filter.AwsExtensionsKt$AwsAuth$2$1.invoke(awsExtensions.kt:40)
	at org.http4k.filter.AwsExtensionsKt$AwsAuth$2$1.invoke(awsExtensions.kt:37)
	at org.http4k.filter.ClientFilters$SetXForwardedHost$1$1.invoke(ClientFilters.kt:89)
	at org.http4k.filter.ClientFilters$SetXForwardedHost$1$1.invoke(ClientFilters.kt:88)
	at org.http4k.filter.ClientFilters$SetHostFrom$1$1.invoke(ClientFilters.kt:70)
	at org.http4k.filter.ClientFilters$SetHostFrom$1$1.invoke(ClientFilters.kt:69)
	at org.http4k.filter.ClientFilters$SetBaseUriFrom$1$1.invoke(ClientFilters.kt:80)
	at org.http4k.filter.ClientFilters$SetBaseUriFrom$1$1.invoke(ClientFilters.kt:80)
	at org.http4k.filter.ClientFilters$SetHostFrom$1$1.invoke(ClientFilters.kt:70)
	at org.http4k.filter.ClientFilters$SetHostFrom$1$1.invoke(ClientFilters.kt:69)
	at org.http4k.core.Http4kKt$then$2$1.invoke(Http4k.kt:15)
	at org.http4k.core.Http4kKt$then$2$1.invoke(Http4k.kt:15)
	at org.http4k.connect.amazon.s3.HttpS3BucketKt$Http$1.invoke(HttpS3Bucket.kt:36)
	at org.http4k.connect.amazon.s3.S3bucketExtensionsKt.getObject(s3bucketExtensions.kt:66)
```

Not sure if I am missing something which I need to change or if something broke between these versions

**Comment by daviddenton** [comment]
Try to upgrade connect and see if that helps. If it doesn't then we can push out a new version ASAP.

**Comment by AndreVelde** [comment]
Made a mistake with not updating the connection library. Works now as expected
