### ISSUE TITLE
Requests with unknown HTTP method result in uncaught exceptions

### ISSUE THREAD

**Issue by marcin-maciej-seweryn** [http4k/http4k#827]
When server receives a HTTP request with a method other than defined in the `Method` enum, a `IllegalArgumentException` is thrown that is not handled properly which  leads to hanging client connections.

### Steps to reproduce
1. Run a local server
2. Execute in shell `curl -X DEBUG http://localhost:PORT/[RESOURCE_PATH]` where `PORT` is a port number on which server is listening and `RESOURCE_PATH` is an optional path to a resource

### What's the expected result
According to the [HTTP specification](https://www.rfc-editor.org/rfc/rfc2616#section-5.1.1) server should return response with status 501.

### What's the actual result?
The `Method#valueOf` method throws `IllegalArgumentException` which is not handled by `http4k` and is caught by a default Netty handler that only logs it. This results in a "hanging" client connections. 

Here's a example stack trace:
```
14:32:09.810 [nioEventLoopGroup-3-5] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: No enum constant org.http4k.core.Method.DEBUG
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at org.http4k.core.Method.valueOf(http.kt)
        at org.http4k.server.Http4kChannelHandler.asRequest(Netty.kt:64)
        at org.http4k.server.Http4kChannelHandler.channelRead0(Netty.kt:50)
        at org.http4k.server.Http4kChannelHandler.channelRead0(Netty.kt:45)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.opentelemetry.javaagent.shaded.instrumentation.netty.v4_1.internal.server.HttpServerRequestTracingHandler.channelRead(HttpServerRequestTracingHandler.java:49)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Links
- #399 is about adding support for custom methods while this issue is about proper handling of unsupported methods

**Comment by marcin-maciej-seweryn** [comment]
If you agree with the conclusion that 501 should be returned when a request with an unknown method is received, then I can contribute a fix.

**Comment by s4nchez** [comment]
@marcin-maciej-seweryn yes, you’re correct and servers should return 501 in those cases. Good spotting!

Do you have a pressing use case this bug is blocking?

We encourage people to contribute and appreciate your offer, but this is likely require a design change deep in the core library so we need to handle it ourselves.

**Comment by marcin-maciej-seweryn** [comment]
Thanks @s4nchez and @daviddenton for a quick handling of this issue.

Regarding the use case, I have discovered this problem when running security tests against our application built with `http4k`.
Since it was fixed so fast, there's no problem as I'll just updated to the latest `http4k` version.
